apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: wize-demo-data-science
  title: demo data
  description: Create a data science project powered with python
  tags:
    - demo
    - data
    - python
spec:
  owner: web@example.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
